import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import { AppRouterCacheProvider } from '@mui/material-nextjs/v13-appRouter'
import { Providers } from '@/lib/Providers/Providers'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <Providers>
      <html lang="en">
        {/* AppRouterCacheProvider add korar karone Metarial Ui use krle 'use client' add krte hobe nah. server side e auto kaj krbe */}
        <AppRouterCacheProvider>
          <body className={inter.className}>{children}</body>
        </AppRouterCacheProvider>
      </html>
    </Providers>
  )
}
